# Generated by Django 5.2.4 on 2025-08-31 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PointsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_1_points', models.IntegerField(default=10)),
                ('rank_2_points', models.IntegerField(default=6)),
                ('rank_3_points', models.IntegerField(default=3)),
                ('grade_a_points', models.IntegerField(default=10)),
                ('grade_b_points', models.IntegerField(default=6)),
                ('grade_c_points', models.IntegerField(default=3)),
                ('grade_a_threshold', models.IntegerField(default=80)),
                ('grade_b_threshold', models.IntegerField(default=70)),
                ('grade_c_threshold', models.IntegerField(default=60)),
            ],
            options={
                'verbose_name': 'Points Configuration',
                'verbose_name_plural': 'Points Configuration',
            },
        ),
        migrations.CreateModel(
            name='GirlsTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_points', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chest_no', models.PositiveIntegerField(null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('total_points', models.IntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='girls.category')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='girls.girlsteam')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_group', models.BooleanField(default=False, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='girls.category')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(blank=True, null=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=1, null=True)),
                ('points_awarded', models.BooleanField(default=False)),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='girls.contestant')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='girls.program')),
            ],
        ),
        migrations.CreateModel(
            name='GroupParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=200)),
                ('marks', models.IntegerField(blank=True, null=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=1, null=True)),
                ('points_awarded', models.BooleanField(default=False)),
                ('contestants', models.ManyToManyField(to='girls.contestant')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='girls.girlsteam')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='girls.program')),
            ],
        ),
        migrations.CreateModel(
            name='TeamPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='girls.girlsteam')),
            ],
        ),
    ]
