# Generated by Django 5.2.4 on 2025-07-27 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_participation_points_awarded_user_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='schedule_time',
        ),
        migrations.RemoveField(
            model_name='program',
            name='stage',
        ),
    ]
