# Generated by Django 5.2.4 on 2025-07-27 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_program_schedule_time_remove_program_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
