# Generated by Django 5.2.4 on 2025-07-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contestant_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='chest_no',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
