# Generated by Django 5.2.4 on 2025-07-31 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contestant_chest_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participation',
            name='points_awarded',
            field=models.IntegerField(default=False),
        ),
    ]
