# Generated by Django 5.2.4 on 2025-08-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contestant_total_points_team_total_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='points_awarded',
            field=models.BooleanField(default=False),
        ),
    ]
