# Generated by Django 5.2.4 on 2025-08-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_participation_points_awarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_type',
            field=models.CharField(choices=[('solo', 'Solo'), ('group', 'Group')], default='solo', max_length=20),
        ),
    ]
