# Generated by Django 5.2.4 on 2025-08-20 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_program_program_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='program_type',
        ),
    ]
