# Generated by Django 5.2.4 on 2025-08-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_program_program_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_group',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
