# Generated by Django 5.2.4 on 2025-08-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_groupparticipation'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupparticipation',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
