# Generated by Django 5.2.4 on 2025-08-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_groupparticipation_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupparticipation',
            name='grade',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='groupparticipation',
            name='points_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupparticipation',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
