# Generated by Django 5.2.4 on 2025-08-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_groupparticipation_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='group_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='GroupParticipation',
        ),
    ]
