# Generated by Django 5.2.4 on 2025-08-27 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_participation_group_code_participation_is_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='group_code',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='is_group',
        ),
        migrations.CreateModel(
            name='GroupParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('contestants', models.ManyToManyField(related_name='group_participations', to='core.contestant')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.program')),
            ],
        ),
        migrations.AddField(
            model_name='participation',
            name='group_participation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.groupparticipation'),
        ),
    ]
