# Generated by Django 5.2.4 on 2025-08-29 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_groupassign_groupprograms'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_1_points', models.IntegerField(default=10)),
                ('rank_2_points', models.IntegerField(default=6)),
                ('rank_3_points', models.IntegerField(default=3)),
                ('grade_a_points', models.IntegerField(default=10)),
                ('grade_b_points', models.IntegerField(default=6)),
                ('grade_c_points', models.IntegerField(default=3)),
                ('grade_a_threshold', models.IntegerField(default=80)),
                ('grade_b_threshold', models.IntegerField(default=70)),
                ('grade_c_threshold', models.IntegerField(default=60)),
            ],
            options={
                'verbose_name': 'Points Configuration',
                'verbose_name_plural': 'Points Configuration',
            },
        ),
        migrations.RemoveField(
            model_name='groupprograms',
            name='category',
        ),
        migrations.RemoveField(
            model_name='groupparticipation',
            name='group_code',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='group_participation',
        ),
        migrations.AddField(
            model_name='groupparticipation',
            name='grade',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='groupparticipation',
            name='group_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='groupparticipation',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupparticipation',
            name='points_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupparticipation',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupparticipation',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.team'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.team'),
        ),
        migrations.AlterField(
            model_name='groupparticipation',
            name='contestants',
            field=models.ManyToManyField(to='core.contestant'),
        ),
        migrations.DeleteModel(
            name='GroupAssign',
        ),
        migrations.DeleteModel(
            name='GroupPrograms',
        ),
    ]
