# Generated by Django 5.2.4 on 2025-09-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_pointsconfig_remove_groupprograms_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('team', 'Team'), ('off_campus', 'Off_campus')], max_length=10),
        ),
    ]
